apiVersion: v1
kind: Service
metadata:
  name: kuber-default-service
spec:
  selector:
    app: http-server-default
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30001
  type: NodePort